/**
 * 
 */
package entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="person")
public class Person {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private int Aadhar_id;
	@DynamoDBAttribute
	private String person_name;
	@DynamoDBAttribute
	private String gender;
	@DynamoDBAttribute
	private String city;
	@DynamoDBAttribute
	private int age;
	
	@SuppressWarnings("unused")
	private Person_insurence person_insurence;
	
	

}
